Update if-demo.yml

diff --git a/.github/workflows/if-demo.yml b/.github/workflows/if-demo.yml
--- a/.github/workflows/if-demo.yml
+++ b/.github/workflows/if-demo.yml
@@ -50,7 +50,9 @@ jobs:
     if: github.ref_name == 'main' && github.event_name == 'push'
     steps:
       - name: prod deploy
-        run: echo "deploying the code to production environment"
+        run:  |
+          echo "deploying the code to production environment"
+          exit 1  # for failur test case
   SuccessNotify:
     runs-on: ubuntu-latest
     needs: ['qualityChecks','devDeploy','prdDeploy']
@@ -66,5 +68,3 @@ jobs:
       - name: Notify failure
         run: |
           echo "Execution failed"
-          exit 1  # for failur test case
-
